#!/usr/bin/env bash

stops_loop () {
	rm /var/run/myscript.pid
 	exit 0
}
echo "$BASHPID" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2

  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && stops_loop' SIGTERM
  trap 'stops_loop' SIGQUIT
done
