#!/usr/bin/env bash
# This script displays the PID, along with the process name, of processes whose name contain the word bash.
# shellcheck disable=SC2009
# uses pgrep to search for PIDSunder the name bash
PID = $(pgrep -f bash)
for PID in $PID; do
    process = $(pgrep -l -P $pid)
    echo "PID: $PID, Process Name: $process"
