#!/usr/bin/env bash
# This script halts the inifinite loop using kil CMD

stop_loop ()
{
	echo "Terminated"
	exit 0
}
# Terminates at the 15th signal
trap stop_loop SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
