#!/usr/bin/env bash
#This script prints out 1- 100, with Fizzbuzz in certain points of the list
number = 1
while [ $number -ne 101]
do
	if [ $((number % 15)) -eq 0]
	then
		echo "FizzBuzz"
	elif [ $((number % 3)) -eq 0]
	then
		echo "Fizz"
	elif [ $((number % 5)) -eq 0]
	then
		echo "Buzz"
	else
		echo $number
	fi
	((number++))
done
