#!/usr/bin/env bash
# This script loops from 1 to 10, various displays
k = 0
while ((k < 10))
do
	echo "Best School"
	((k++))
	if [$k -eq 3]
	then
		echo "bad luck"
	elif [$k -eq 7]
	then
		echo "good luck"
	fi
done
