#!/usr/bin/env bash
# This script loops from 1 to 10, various displays

k = 0
while ((k < 10))
do
	((k++))
	if [ $k -eq 4]
	then
		echo "bad luck"
	elif [ $k -eq 8]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
